


-- Inserted at 2009-01-09T16:23:33.064Z

update REQUEST_ITEM SET KEY_REQUEST=KEY_ACQUISITION_REQUEST WHERE KEY_ACQUISITION_REQUEST IS NOT NULL;
alter table REQUEST_ITEM DROP COLUMN KEY_ACQUISITION_REQUEST;



