-- Prepare structure

alter table `WORKFLOW_LOG` add column `STATE` text;
alter table `WORKFLOW_PROCESS` add column `ACQUISITION_PROCESS_NUMBER` int(11);
alter table `WORKFLOW_PROCESS` add column `FUND_ALLOCATION_EXPIRATION_DATE` text;
alter table `WORKFLOW_PROCESS` add column `OID_ACQUISITION_AFTER_THE_FACT` bigint(20);
alter table `WORKFLOW_PROCESS` add column `OID_ACQUISITION_REQUEST` bigint(20);
alter table `WORKFLOW_PROCESS` add column `OID_ANNOUNCEMENT` bigint(20);
alter table `WORKFLOW_PROCESS` add column `OID_IMPORT_FILE` bigint(20);
alter table `WORKFLOW_PROCESS` add column `OID_PAYMENT_PROCESS_YEAR` bigint(20);
alter table `WORKFLOW_PROCESS` add column `OID_REQUEST_FOR_PROPOSAL` bigint(20);
alter table `WORKFLOW_PROCESS` add column `OID_REQUEST` bigint(20);
alter table `WORKFLOW_PROCESS` add column `PROCESS_CLASSIFICATION` text;
alter table `WORKFLOW_PROCESS` add column `SKIP_SUPPLIER_FUND_ALLOCATION` tinyint(1);
alter table `WORKFLOW_PROCESS` add index (`OID_IMPORT_FILE`);
alter table `WORKFLOW_PROCESS` add index (`OID_PAYMENT_PROCESS_YEAR`);

-- Migrate GenericProcess => WorkflowProcess

insert into WORKFLOW_PROCESS(OID,ACQUISITION_PROCESS_NUMBER, FUND_ALLOCATION_EXPIRATION_DATE, ID_INTERNAL, OID_ACQUISITION_AFTER_THE_FACT, OID_ACQUISITION_REQUEST, OID_ANNOUNCEMENT, OID_CURRENT_OWNER, OID_IMPORT_FILE, OID_PAYMENT_PROCESS_YEAR, OID_REQUEST, OID_REQUEST_FOR_PROPOSAL, PROCESS_CLASSIFICATION, OJB_CONCRETE_CLASS, SKIP_SUPPLIER_FUND_ALLOCATION) 
select OID,ACQUISITION_PROCESS_NUMBER, FUND_ALLOCATION_EXPIRATION_DATE, ID_INTERNAL, OID_ACQUISITION_AFTER_THE_FACT, OID_ACQUISITION_REQUEST, OID_ANNOUNCEMENT, OID_CURRENT_OWNER, OID_IMPORT_FILE, OID_PAYMENT_PROCESS_YEAR, OID_REQUEST, OID_REQUEST_FOR_PROPOSAL, PROCESS_CLASSIFICATION, OJB_CONCRETE_CLASS, SKIP_SUPPLIER_FUND_ALLOCATION FROM GENERIC_PROCESS;

-- Migrate ProcessComment => WorkflowProcessComment
insert into WORKFLOW_PROCESS_COMMENT(ID_INTERNAL,COMMENT,DATE,OID_COMMENTER,OID_PROCESS) 
select ID_INTERNAL,COMMENT,DATE,OID_COMMENTER,OID_PROCESS FROM PROCESS_COMMENT;

-- Generate WorkflowProcessComment OIDs

select @CLASS_ID:=DOMAIN_CLASS_ID FROM FF$DOMAIN_CLASS_INFO WHERE DOMAIN_CLASS_NAME='module.workflow.domain.WorkflowProcessComment';

update WORKFLOW_PROCESS_COMMENT set OID = ((@CLASS_ID<<32) + ID_INTERNAL);

-- Migrate GenericLog => WorkflowLog

insert into WORKFLOW_LOG(OID,ID_INTERNAL,OID_ACTIVITY_EXECUTOR,OID_PROCESS,OJB_CONCRETE_CLASS,OPERATION,WHEN_OPERATION_WAS_RAN,STATE)
select OID,ID_INTERNAL,OID_EXECUTOR,OID_PROCESS,OJB_CONCRETE_CLASS,OPERATION,WHEN_OPERATION_WAS_RAN,STATE FROM GENERIC_LOG;

-- Connect Workflow Entities to WorkflowSystem

select @WFS:=OID FROM WORKFLOW_SYSTEM;
update WORKFLOW_PROCESS SET OID_WORKFLOW_SYSTEM=@WFS;
update WORKFLOW_PROCESS_COMMENT SET OID_WORKFLOW_SYSTEM=@WFS;
update WORKFLOW_LOG SET OID_WORKFLOW_SYSTEM=@WFS;

-- Migrate *-* relation PersonReadComment to UserReadComment

insert into USER_READ_COMMENT(OID_USER,OID_WORKFLOW_PROCESS_COMMENT)
select OID_USER,OID_PROCESS_COMMENT FROM PERSON_READ_COMMENT;

-- Migrate Comment Conection in the UserReadComment table
-- Temporary table is being used due to performance issues

create TEMPORARY table COMMENT_RESOLUTION(ID_INTERNAL int(11), OID1 bigint(20), OID2 bigint(20));
insert into COMMENT_RESOLUTION(ID_INTERNAL,OID1,OID2) 
select PC.ID_INTERNAL, PC.OID, WPC.OID FROM PROCESS_COMMENT PC, WORKFLOW_PROCESS_COMMENT WPC WHERE PC.ID_INTERNAL=WPC.ID_INTERNAL;

update USER_READ_COMMENT URC, COMMENT_RESOLUTION CR SET 
URC.OID_WORKFLOW_PROCESS_COMMENT=CR.OID2 WHERE URC.OID_WORKFLOW_PROCESS_COMMENT=CR.OID1;

DROP TEMPORARY TABLE COMMENT_RESOLUTION;
