UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='SubmitForApproval' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.SubmitForApproval' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='Approve' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.Approve' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='CancelRefundProcess' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.CancelRefundProcess' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='GenericAddPayingUnit' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.GenericAddPayingUnit' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='CreateRefundItem' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.CreateRefundItem' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='EditRefundItem' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.EditRefundItem' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='DeleteRefundItem' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.DeleteRefundItem' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='UnSubmitForApproval' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.UnSubmitForApproval' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='ProjectFundAllocation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.ProjectFundAllocation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='GenericRemovePayingUnit' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.GenericRemovePayingUnit' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='GenericAssignPayingUnitToItem' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.GenericAssignPayingUnitToItem' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='FundAllocation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.FundAllocation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='Authorize' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.Authorize' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='UnSubmitForFundAllocation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.UnSubmitForFundAllocation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='CreateRefundInvoice' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.CreateRefundInvoice' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='SubmitForInvoiceConfirmation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.SubmitForInvoiceConfirmation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='UnApprove' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.UnApprove' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='RemoveProjectFundAllocation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.RemoveProjectFundAllocation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='ChangeFinancersAccountingUnit' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.ChangeFinancersAccountingUnit' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='RemoveFundAllocation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.RemoveFundAllocation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='RemoveRefundInvoice' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.RemoveRefundInvoice' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='EditRefundInvoice' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.EditRefundInvoice' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='ConfirmInvoices' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.ConfirmInvoices' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='UnAuthorize' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.UnAuthorize' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='DistributeRealValuesForPayingUnits' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.DistributeRealValuesForPayingUnits' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='AllocateProjectFundsPermanently' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.AllocateProjectFundsPermanently' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='AllocateFundsPermanently' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.AllocateFundsPermanently' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='RefundPerson' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.RefundPerson' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='RemoveFundsPermanentlyAllocated' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.RemoveFundsPermanentlyAllocated' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='UnconfirmInvoices' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.UnconfirmInvoices' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='RevertInvoiceConfirmationSubmition' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.RevertInvoiceConfirmationSubmition' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='SetSkipSupplierFundAllocation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.SetSkipSupplierFundAllocation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='UnsetSkipSupplierFundAllocation' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.activities.UnsetSkipSupplierFundAllocation' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';
UPDATE WORKFLOW_LOG WL, WORKFLOW_PROCESS WP set WL.OPERATION='RemovePermanentProjectFunds' WHERE WL.OPERATION='pt.ist.expenditureTrackingSystem.domain.acquisitions.activities.RemovePermanentProjectFunds' AND WL.OID_PROCESS=WP.OID AND WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';

update WORKFLOW_LOG WL, WORKFLOW_PROCESS WP SET WL.OJB_CONCRETE_CLASS='module.workflow.domain.ActivityLog' WHERE
WL.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.processes.GenericLog' AND WL.OID_PROCESS=WP.OID AND
WP.OJB_CONCRETE_CLASS='pt.ist.expenditureTrackingSystem.domain.acquisitions.refund.RefundProcess';


select @CLASS_ID := DOMAIN_CLASS_ID FROM FF$DOMAIN_CLASS_INFO WHERE DOMAIN_CLASS_NAME='module.workflow.domain.ActivityLog';

update WORKFLOW_LOG SET OID = (@CLASS_ID << 32) + ID_INTERNAL WHERE OJB_CONCRETE_CLASS='module.workflow.domain.ActivityLog' AND (OID >> 32) <> @CLASS_ID;