-- Moving Person to User in comments
update PROCESS_COMMENT PC, PERSON P SET OID_COMMENTER=P.OID_USER WHERE PC.OID_COMMENTER=P.OID;

alter table PERSON_READ_COMMENT change OID_PERSON OID_USER bigint(20) unsigned;
update PERSON_READ_COMMENT PRC, PERSON P SET PRC.OID_USER=P.OID_USER WHERE PRC.OID_USER=P.OID;

-- Moving Person to User in Logs

update GENERIC_LOG GL, PERSON P SET GL.OID_EXECUTOR=P.OID_USER WHERE GL.OID_EXECUTOR=P.OID;

-- Moving Person to User in Take System

update GENERIC_PROCESS GP, PERSON P SET GP.OID_CURRENT_OWNER=P.OID_USER WHERE GP.OID_CURRENT_OWNER=P.OID;
